#!/bin/sh
#
#SBATCH --job-name=indirectGroupwiseMeasures_ICI_PROB_OCCURENCE_PROPAGATED_1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem-per-cpu=4096
#SBATCH --partition=batch
#SBATCH --time=28-00:00:00
#
javac -cp ../indirectGroupwiseMeasures/ICI_PROB_OCCURENCE_PROPAGATED/SIM_GROUPWISE_AVERAGE/SIM_PAIRWISE_DAG_NODE_FEATURE_TVERSKY_RATIO_MODEL/Gene.java:../libs/slib-dist-0.9-all-jar.jar:../indirectGroupwiseMeasures/ICI_PROB_OCCURENCE_PROPAGATED/SIM_GROUPWISE_AVERAGE/SIM_PAIRWISE_DAG_NODE_FEATURE_TVERSKY_RATIO_MODEL/ ../indirectGroupwiseMeasures/ICI_PROB_OCCURENCE_PROPAGATED/SIM_GROUPWISE_AVERAGE/SIM_PAIRWISE_DAG_NODE_FEATURE_TVERSKY_RATIO_MODEL/Exp5.java
java -cp  ../indirectGroupwiseMeasures/ICI_PROB_OCCURENCE_PROPAGATED/SIM_GROUPWISE_AVERAGE/SIM_PAIRWISE_DAG_NODE_FEATURE_TVERSKY_RATIO_MODEL/:../libs/slib-dist-0.9-all-jar.jar Exp5
